project:
  type: website

website:
  title: "qtm350-summer-quiz02"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: life-gdp.qmd
        text: Life Expectancy and GDP per Capita
      - href: life-population.qmd
        text: Life Expectancy and Population
      - href: country.qmd
        text: Country Analysis
      - about.qmd

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true



